version: '3.4'

volumes:
  sqlserver_volume:

networks:
  backend:

services:
  jobopportunitymicroservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 #;https://+:443
    ports:
      - "9050:80"
      #- "9051:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - backend

  sqlserver.db:
    ports:
      - 8822:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abcd@1234
    volumes:
      - sqlserver_volume:/var/opt/mssql
    networks:
      - backend